version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Setup build tools
          command: apk add --no-progress gcc libc-dev make valgrind cppcheck clang clang-format
      - run:
          name: Code Format
          command: "! make check_format 2>&1 | grep -c '@@' > /dev/null"
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: make test
      - store_artifacts:
          path: bin/fist
